#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import sys
import argparse
import inspect

TEMPLATE = """\
extern const char {0}[];
const char {0}[] = {{{1}, 0}};

"""

def main():
    """Generate a C++ header from another file's contents."""
    parser = argparse.ArgumentParser(description=inspect.getdoc(main))
    parser.add_argument('-n', '--name', type=str, default='kSource_api')
    parser.add_argument('-o', '--output', type=argparse.FileType('w'),
                        default=sys.stdout)
    parser.add_argument('input', type=argparse.FileType('r'))

    args = parser.parse_args()

    contents = args.input.read()
    code = ', '.join(str(ord(ch)) for ch in contents)
    header = TEMPLATE.format(args.name, code)

    args.output.write(header)

if __name__ == '__main__':
    sys.exit(main())
